name: example
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.1.0-nullsafety.1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.3
  flutter:
    sdk: flutter
  juxtapose:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
